### ISSUE TITLE
Create Main Menu

### ISSUE THREAD

**Issue by fsujk12d** [fsujk12d/CEN4090L#1]
Add three buttons onto the main menu - Layout contained in app/src/main/res/layout/activity_main.xml, Java is in app/src/main/java/com/cen4090/mobilympics/MainActivity.java.

Button 1 should say Host Game
Button 2 should say Find Game
Button 3 should say Options

Style need not be applied at this time.

**Comment by arliehaire** [comment]
Main Menu has been achieved
